#!/usr/bin/env bash

set -e

# Time-like tree.
tlynx -f -o time simulate -t 1 -n 18 -H 0.3 -S "[0]"

./renameTips.py time.tree
mv time_renamed.dnd time_renamed.tree

# Substitution-like tree.
cmd="./alterBranchLengths.py time_renamed.tree 0.01 0.05 0.5 0.2 0.01 substitution.tree y"
echo $cmd > substitution.log
$cmd >> substitution.log

# Alignment.
slynx -f -o alignment simulate -t substitution.tree -s JC -l 5000 -S "[0]"

./unrootTree.py substitution.tree
mv substitution_unrooted.dnd substitution_unrooted.tree

